In [26]:
import pandas as pd
import os
from time import time

In [27]:
# Récupération de la liste des fichiers Excel

file_list = [ f for f in os.listdir('.') if (os.path.isfile(os.path.join('.',f)) & f.lower().endswith('.csv')) ]
print(file_list)

['export_gps_iris_0-10000.csv', 'export_gps_iris_10000-90000.csv', 'export_gps_iris_1009200-1019200.csv', 'export_gps_iris_1019200-1029200.csv', 'export_gps_iris_1029200-1035000.csv', 'export_gps_iris_1037750-1047750.csv', 'export_gps_iris_1037750_1055750.csv', 'export_gps_iris_150000-160000.csv', 'export_gps_iris_160000-170000.csv', 'export_gps_iris_170000-180000.csv', 'export_gps_iris_180000-190000.csv', 'export_gps_iris_180000-200000.csv', 'export_gps_iris_190000-200000.csv', 'export_gps_iris_200001-240001.csv', 'export_gps_iris_240001-300001.csv', 'export_gps_iris_300001-400001.csv', 'export_gps_iris_400000-500000.csv', 'export_gps_iris_500000-510000.csv', 'export_gps_iris_510000-520000.csv', 'export_gps_iris_520000-530000.csv', 'export_gps_iris_530000-540000.csv', 'export_gps_iris_530000-600000.csv', 'export_gps_iris_540000-550000.csv', 'export_gps_iris_550000-560000.csv', 'export_gps_iris_560000-570000.csv', 'export_gps_iris_570000-580000.csv', 'export_gps_iris_580000-590000.csv', 'export_gps_iris_590000-600000.csv', 'export_gps_iris_600000-610000.csv', 'export_gps_iris_610000-620000.csv', 'export_gps_iris_620000-630000.csv', 'export_gps_iris_630000-640000.csv', 'export_gps_iris_640000-650000.csv', 'export_gps_iris_650000-660000.csv', 'export_gps_iris_660000-670000.csv', 'export_gps_iris_670000-680000.csv', 'export_gps_iris_680000-690000.csv', 'export_gps_iris_690000-700000.csv', 'export_gps_iris_700000-710000.csv', 'export_gps_iris_710000-720000.csv', 'export_gps_iris_720000-730000.csv', 'export_gps_iris_730000-740000.csv', 'export_gps_iris_740000-750000.csv', 'export_gps_iris_750000-760000.csv', 'export_gps_iris_760000-770000.csv', 'export_gps_iris_770000_785100.csv', 'export_gps_iris_785100-795100.csv', 'export_gps_iris_795100-805100.csv', 'export_gps_iris_805100-815100.csv', 'export_gps_iris_815100_819100.csv', 'export_gps_iris_819100-829100.csv', 'export_gps_iris_829100-839100.csv', 'export_gps_iris_839100-849100.csv', 'export_gps_iris_849100-859100.csv', 'export_gps_iris_859100-869100.csv', 'export_gps_iris_869100-879100.csv', 'export_gps_iris_879100-900000.csv', 'export_gps_iris_90000-150000.csv', 'export_gps_iris_900000-910000.csv', 'export_gps_iris_910000-920000.csv', 'export_gps_iris_920000-930000.csv', 'export_gps_iris_930000-940000.csv', 'export_gps_iris_940000-950000.csv', 'export_gps_iris_950000-979200.csv', 'export_gps_iris_979200-989200.csv', 'export_gps_iris_989200-999200.csv', 'export_gps_iris_999200-1009200.csv', 'export_gps_iris_lyon_marseille.csv']

In [28]:
adresses = pd.DataFrame(data=[])
nb_files = 0

heure_debut = time()

for f in file_list:
    df = pd.read_csv(f)
    adresses = pd.concat([adresses, df])
    nb_files += 1
    print(f)

heure_fin = time()
temps = heure_fin - heure_debut

print("\n")
print("Task achieved in", temps, "s")
print("Nb files", nb_files)

export_gps_iris_0-10000.csv
export_gps_iris_10000-90000.csv
export_gps_iris_1009200-1019200.csv
export_gps_iris_1019200-1029200.csv
export_gps_iris_1029200-1035000.csv
export_gps_iris_1037750-1047750.csv
export_gps_iris_1037750_1055750.csv
export_gps_iris_150000-160000.csv
export_gps_iris_160000-170000.csv
export_gps_iris_170000-180000.csv
export_gps_iris_180000-190000.csv
export_gps_iris_180000-200000.csv
export_gps_iris_190000-200000.csv
export_gps_iris_200001-240001.csv
export_gps_iris_240001-300001.csv
export_gps_iris_300001-400001.csv
export_gps_iris_400000-500000.csv
export_gps_iris_500000-510000.csv
export_gps_iris_510000-520000.csv
export_gps_iris_520000-530000.csv
export_gps_iris_530000-540000.csv
export_gps_iris_530000-600000.csv
export_gps_iris_540000-550000.csv
export_gps_iris_550000-560000.csv
export_gps_iris_560000-570000.csv
export_gps_iris_570000-580000.csv
export_gps_iris_580000-590000.csv
export_gps_iris_590000-600000.csv
export_gps_iris_600000-610000.csv
export_gps_iris_610000-620000.csv
export_gps_iris_620000-630000.csv
export_gps_iris_630000-640000.csv
export_gps_iris_640000-650000.csv
export_gps_iris_650000-660000.csv
export_gps_iris_660000-670000.csv
export_gps_iris_670000-680000.csv
export_gps_iris_680000-690000.csv
export_gps_iris_690000-700000.csv
export_gps_iris_700000-710000.csv
export_gps_iris_710000-720000.csv
export_gps_iris_720000-730000.csv
export_gps_iris_730000-740000.csv
export_gps_iris_740000-750000.csv
export_gps_iris_750000-760000.csv
export_gps_iris_760000-770000.csv
export_gps_iris_770000_785100.csv
export_gps_iris_785100-795100.csv
export_gps_iris_795100-805100.csv
export_gps_iris_805100-815100.csv
export_gps_iris_815100_819100.csv
export_gps_iris_819100-829100.csv
export_gps_iris_829100-839100.csv
export_gps_iris_839100-849100.csv
export_gps_iris_849100-859100.csv
export_gps_iris_859100-869100.csv
export_gps_iris_869100-879100.csv
export_gps_iris_879100-900000.csv
export_gps_iris_90000-150000.csv
export_gps_iris_900000-910000.csv
export_gps_iris_910000-920000.csv
export_gps_iris_920000-930000.csv
export_gps_iris_930000-940000.csv
export_gps_iris_940000-950000.csv
export_gps_iris_950000-979200.csv
export_gps_iris_979200-989200.csv
export_gps_iris_989200-999200.csv
export_gps_iris_999200-1009200.csv
export_gps_iris_lyon_marseille.csv


Task achieved in 21.60973858833313 s
Nb files 68

In [29]:
import numpy as np
adresses['Code postal'] = adresses['Code postal'].fillna(-1).astype(int).astype(str).replace('-1', np.nan)
adresses['Code postal 5 chiffres'] = adresses['Code postal'].apply(lambda x: x.zfill(5) if len(str(x)) == 4 else x).astype(str)
adresses.head()

,Unnamed: 0,No voie,Type de voie,Voie,Code postal,Commune,Ville,Adresse,INSEE_COM,Commune_Lat,Commune_Lon,code_iris,lon,lat,Code departement,Code commune,Code commune INSEE,coordonnees_gps,Code postal 5 chiffres
0,0,NaN,NaN,FORTUNAT,1250,CEYZERIAT,1250 CEYZERIAT,FORTUNAT 1250 CEYZERIAT,1072.0,46.183217,5.320072,10720000.0,5.323007,46.173753,NaN,NaN,NaN,NaN,01250
1,1,NaN,NaN,TERRES DES CINQ SAULES,1290,LAIZ,1290 LAIZ,TERRES DES CINQ SAULES 1290 LAIZ,1203.0,46.246992,4.899335,12030000.0,4.892457,46.246330,NaN,NaN,NaN,NaN,01290
2,2,NaN,NaN,BOIS DU CHAMP RION,1290,LAIZ,1290 LAIZ,BOIS DU CHAMP RION 1290 LAIZ,1203.0,46.246992,4.899335,12030000.0,4.892457,46.246330,NaN,NaN,NaN,NaN,01290
3,3,NaN,NaN,EN COROBERT,1290,LAIZ,1290 LAIZ,EN COROBERT 1290 LAIZ,1203.0,46.246992,4.899335,12030000.0,4.881913,46.248368,NaN,NaN,NaN,NaN,01290
4,4,NaN,RUE,DE LA CHARTREUSE,1960,PERONNAS,1960 PERONNAS,RUE DE LA CHARTREUSE 1960 PERONNAS,1289.0,46.171190,5.218022,12890102.0,5.227583,46.184979,NaN,NaN,NaN,NaN,01960

In [30]:
adresses['Code departement'] = adresses['Code postal 5 chiffres'].str[0:2].astype(str)
adresses.head()

,Unnamed: 0,No voie,Type de voie,Voie,Code postal,Commune,Ville,Adresse,INSEE_COM,Commune_Lat,Commune_Lon,code_iris,lon,lat,Code departement,Code commune,Code commune INSEE,coordonnees_gps,Code postal 5 chiffres
0,0,NaN,NaN,FORTUNAT,1250,CEYZERIAT,1250 CEYZERIAT,FORTUNAT 1250 CEYZERIAT,1072.0,46.183217,5.320072,10720000.0,5.323007,46.173753,01,NaN,NaN,NaN,01250
1,1,NaN,NaN,TERRES DES CINQ SAULES,1290,LAIZ,1290 LAIZ,TERRES DES CINQ SAULES 1290 LAIZ,1203.0,46.246992,4.899335,12030000.0,4.892457,46.246330,01,NaN,NaN,NaN,01290
2,2,NaN,NaN,BOIS DU CHAMP RION,1290,LAIZ,1290 LAIZ,BOIS DU CHAMP RION 1290 LAIZ,1203.0,46.246992,4.899335,12030000.0,4.892457,46.246330,01,NaN,NaN,NaN,01290
3,3,NaN,NaN,EN COROBERT,1290,LAIZ,1290 LAIZ,EN COROBERT 1290 LAIZ,1203.0,46.246992,4.899335,12030000.0,4.881913,46.248368,01,NaN,NaN,NaN,01290
4,4,NaN,RUE,DE LA CHARTREUSE,1960,PERONNAS,1960 PERONNAS,RUE DE LA CHARTREUSE 1960 PERONNAS,1289.0,46.171190,5.218022,12890102.0,5.227583,46.184979,01,NaN,NaN,NaN,01960

In [31]:
adresses.shape

(1198193, 19)

In [32]:
pd.set_option('display.max_rows', 100)

In [33]:
adresses.groupby('Code departement')['Adresse'].count().reset_index()

   Code departement  Adresse
0                01    11728
1                02    12886
2                03     6905
3                04     3660
4                05     2726
5                06    17242
6                07     6730
7                08     6777
8                09     4560
9                10     5956
10               11    13429
11               12     1828
12               13    33526
13               14     5308
14               15     2081
15               16    12263
16               17    14412
17               18     9240
18               19     5895
19               20     1924
20               21     4948
21               22    32289
22               23    11642
23               24    19437
24               25     4239
25               26     6470
26               27     6833
27               28    11662
28               29     5491
29               30    19141
30               31    10415
31               32     5348
32               33    36659
33               34    15787
34               35    35586
35               36     2980
36               37    10793
37               38     9536
38               39    10173
39               40    11213
40               41    10183
41               42    14954
42               43     6470
43               44    35802
44               45    13410
45               46     1773
46               47     9694
47               48     2348
48               49    22938
49               50    20160
50               51    21864
51               52     6644
52               53    22204
53               54    30518
54               55     2740
55               56    35810
56               58    11336
57               59    44980
58               60    16565
59               61     5159
60               62    22311
61               63    11160
62               64     9692
63               65     3270
64               66     3159
65               69    23575
66               70     7079
67               71     9950
68               72    15635
69               73     4447
70               74    11925
71               75    31554
72               76    15773
73               77    25564
74               78    19988
75               79    11318
76               80    11065
77               81     4491
78               82     5756
79               83    10467
80               84     5852
81               85    23575
82               86    11817
83               87    10565
84               88    11656
85               89    11244
86               90     2279
87               91    16826
88               92    11689
89               93    12264
90               94    13562
91               95    16140
92               97     5992
93               na     1283

In [34]:
adresses = adresses.drop_duplicates(keep = "last")

In [35]:
adresses.groupby('Code departement')['Adresse'].count().reset_index()

   Code departement  Adresse
0                01    11728
1                02    12886
2                03     6905
3                04     3660
4                05     2726
5                06    17242
6                07     6730
7                08     6777
8                09     4560
9                10     5956
10               11    13429
11               12     1828
12               13    33526
13               14     5308
14               15     2081
15               16    12263
16               17    14412
17               18     9240
18               19     5895
19               20     1924
20               21     4948
21               22    23691
22               23     5821
23               24    13865
24               25     4239
25               26     6470
26               27     6833
27               28    11662
28               29     5491
29               30    19141
30               31    10415
31               32     5348
32               33    36656
33               34    15787
34               35    35586
35               36     2980
36               37    10793
37               38     9536
38               39    10173
39               40    11213
40               41    10183
41               42    14954
42               43     6470
43               44    35802
44               45    13410
45               46     1773
46               47     9694
47               48     2348
48               49    22938
49               50    18819
50               51    10932
51               52     3322
52               53    11102
53               54    15259
54               55     1370
55               56    17905
56               58     5668
57               59    41935
58               60    16565
59               61     5159
60               62    22311
61               63    11160
62               64     9692
63               65     3270
64               66     3159
65               69    23575
66               70     7079
67               71     9950
68               72    15635
69               73     4447
70               74    11925
71               75    21601
72               76    15773
73               77    25564
74               78    19988
75               79    11318
76               80    11065
77               81     4491
78               82     5756
79               83    10467
80               84     5852
81               85    23575
82               86    11817
83               87    10565
84               88    11656
85               89    11244
86               90     2279
87               91    16826
88               92    11689
89               93    12264
90               94    13562
91               95    16140
92               97     5952
93               na     1214

In [36]:
adresses.shape

(1098193, 19)

In [37]:
adresses.head()

,Unnamed: 0,No voie,Type de voie,Voie,Code postal,Commune,Ville,Adresse,INSEE_COM,Commune_Lat,Commune_Lon,code_iris,lon,lat,Code departement,Code commune,Code commune INSEE,coordonnees_gps,Code postal 5 chiffres
0,0,NaN,NaN,FORTUNAT,1250,CEYZERIAT,1250 CEYZERIAT,FORTUNAT 1250 CEYZERIAT,1072.0,46.183217,5.320072,10720000.0,5.323007,46.173753,01,NaN,NaN,NaN,01250
1,1,NaN,NaN,TERRES DES CINQ SAULES,1290,LAIZ,1290 LAIZ,TERRES DES CINQ SAULES 1290 LAIZ,1203.0,46.246992,4.899335,12030000.0,4.892457,46.246330,01,NaN,NaN,NaN,01290
2,2,NaN,NaN,BOIS DU CHAMP RION,1290,LAIZ,1290 LAIZ,BOIS DU CHAMP RION 1290 LAIZ,1203.0,46.246992,4.899335,12030000.0,4.892457,46.246330,01,NaN,NaN,NaN,01290
3,3,NaN,NaN,EN COROBERT,1290,LAIZ,1290 LAIZ,EN COROBERT 1290 LAIZ,1203.0,46.246992,4.899335,12030000.0,4.881913,46.248368,01,NaN,NaN,NaN,01290
4,4,NaN,RUE,DE LA CHARTREUSE,1960,PERONNAS,1960 PERONNAS,RUE DE LA CHARTREUSE 1960 PERONNAS,1289.0,46.171190,5.218022,12890102.0,5.227583,46.184979,01,NaN,NaN,NaN,01960

In [38]:
adresses = adresses.drop(columns = {'Unnamed: 0'})

In [40]:
adresses.to_csv('03 - export_gps_iris_ALL.csv')