# Objectif du script : 
- Merger toutes les bases : 
    - DVF avec coordonnées GPS
    - Base Loyers
    - Base Equipements (à partir des codes IRIS)
    - Base Revenus
    - Base Population
    - Base DPE (diagnostics énergétiques)

In [56]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [57]:
year = '2020'

In [58]:
df = pd.read_csv('./databases/inter/02C - dvf_with_gps_iris_' + year + '.csv', dtype = {'code_iris_clean': str,
                                                                                             'Code departement' : str,
                                                                                             'Code postal 5 chiffres' : str,
                                                                                             'Code commune INSEE': str})
df.head()

C:\Users\olivier\anaconda\envs\Geo\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (18,20,22,35) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Unnamed: 0,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain,Code commune INSEE,Ville,Adresse,Prix m2,Paris,dep_name,region_name,Mer,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,code_iris_clean
0,0,1,02/01/2020,Vente,268800.0,14.0,NaN,RUE,0411,DE L'ARCADE,75008.0,PARIS,75,108,NaN,BS,136,NaN,31,NaN,8.0,22.72,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,24.0,1.0,NaN,NaN,0.0,75108,75008 PARIS 08,14 RUE DE L'ARCADE 75008 PARIS,11200.000000,1,Paris,Île-de-France,0,NaN,NaN,2.323688,48.871652,75008,751083106
1,1,1,06/01/2020,Vente,878378.0,9.0,NaN,BD,5888,DE LA MADELEINE,75001.0,PARIS,75,101,NaN,BC,41,NaN,14,66.64,15.0,NaN,40.0,NaN,NaN,NaN,NaN,NaN,3,2.0,Appartement,NaN,66.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,9 BD DE LA MADELEINE 75001 PARIS,13308.757576,1,Paris,Île-de-France,0,NaN,NaN,2.326961,48.869560,75001,751010402
2,2,1,10/01/2020,Vente,680000.0,10.0,NaN,RUE,1200,DU BOURG L'ABBE,75003.0,PARIS,75,103,NaN,AV,6,NaN,9,50.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,51.0,2.0,NaN,NaN,0.0,75103,75003 PARIS 03,10 RUE DU BOURG L'ABBE 75003 PARIS,13333.333333,1,Paris,Île-de-France,0,NaN,NaN,2.351889,48.864062,75003,751031204
3,3,1,08/01/2020,Vente,370000.0,79.0,NaN,RUE,0420,DES ARCHIVES,75003.0,PARIS,75,103,NaN,AI,49,NaN,35,22.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,21.0,1.0,NaN,NaN,0.0,75103,75003 PARIS 03,79 RUE DES ARCHIVES 75003 PARIS,17619.047619,1,Paris,Île-de-France,0,NaN,NaN,2.359887,48.863220,75003,751031003
4,4,1,09/01/2020,Vente,741500.0,131.0,NaN,RUE,8525,SAINT DENIS,75001.0,PARIS,75,101,NaN,AQ,107,NaN,23,61.41,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,61.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,131 RUE SAINT DENIS 75001 PARIS,12155.737705,1,Paris,Île-de-France,0,NaN,NaN,2.347447,48.858758,75001,751010101

In [59]:
# On ajoute Surface Terrain = 0 lorsque NaN (la plupart du temps, il s'agit d'appartements qui n'ont par définition pas de terrain)
df['Surface terrain'] = df['Surface terrain'].fillna(0)

## Ajout de la base permanente des équipements (BPE)
Cette base comptabilise le nombre d'équipements par code IRIS (code quartier)

In [60]:
bpe = pd.read_csv('./databases/inter/03A - equipements_nb_clean.csv', dtype = {'code_iris_clean': str})
bpe.head()

,code_iris_clean,Alimentation,Aéroport,Baignade,Banques,Boulangerie,Camping,Cinéma,Collège ou lycée,Crèche,Ecole mat et primaire,Ecole sup,Etab hospi,Gare,Gare nationale,Hotels,Info touristique,Parcours sportif/santé,Pharmacie,Police ou gendarmerie,Port plaisance,Restaurants,Resto U,Résidence U,Salle multisport
0,010010000,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,010040101,6,0,0,1,3,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,10,0,0,3
2,010040102,4,0,0,0,2,0,0,0,0,3,1,0,1,0,0,0,0,1,0,0,18,0,0,0
3,010040201,2,0,0,5,4,0,1,2,1,4,0,0,0,0,0,0,0,4,0,0,12,0,0,0
4,010040202,3,0,0,6,1,0,0,1,1,0,0,3,0,0,1,1,1,0,0,0,5,0,0,2

In [61]:
df_new = df.merge(bpe, on = "code_iris_clean", how = "left")
df_new.head()

,Unnamed: 0,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain,Code commune INSEE,Ville,Adresse,Prix m2,Paris,dep_name,region_name,Mer,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,code_iris_clean,Alimentation,Aéroport,Baignade,Banques,Boulangerie,Camping,Cinéma,Collège ou lycée,Crèche,Ecole mat et primaire,Ecole sup,Etab hospi,Gare,Gare nationale,Hotels,Info touristique,Parcours sportif/santé,Pharmacie,Police ou gendarmerie,Port plaisance,Restaurants,Resto U,Résidence U,Salle multisport
0,0,1,02/01/2020,Vente,268800.0,14.0,NaN,RUE,0411,DE L'ARCADE,75008.0,PARIS,75,108,NaN,BS,136,NaN,31,NaN,8.0,22.72,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,24.0,1.0,NaN,NaN,0.0,75108,75008 PARIS 08,14 RUE DE L'ARCADE 75008 PARIS,11200.000000,1,Paris,Île-de-France,0,NaN,NaN,2.323688,48.871652,75008,751083106,5.0,0.0,0.0,14.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,6.0,0.0,2.0,0.0,0.0,93.0,0.0,0.0,0.0
1,1,1,06/01/2020,Vente,878378.0,9.0,NaN,BD,5888,DE LA MADELEINE,75001.0,PARIS,75,101,NaN,BC,41,NaN,14,66.64,15.0,NaN,40.0,NaN,NaN,NaN,NaN,NaN,3,2.0,Appartement,NaN,66.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,9 BD DE LA MADELEINE 75001 PARIS,13308.757576,1,Paris,Île-de-France,0,NaN,NaN,2.326961,48.869560,75001,751010402,4.0,0.0,0.0,22.0,5.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,12.0,8.0,0.0,4.0,1.0,0.0,87.0,0.0,0.0,0.0
2,2,1,10/01/2020,Vente,680000.0,10.0,NaN,RUE,1200,DU BOURG L'ABBE,75003.0,PARIS,75,103,NaN,AV,6,NaN,9,50.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,51.0,2.0,NaN,NaN,0.0,75103,75003 PARIS 03,10 RUE DU BOURG L'ABBE 75003 PARIS,13333.333333,1,Paris,Île-de-France,0,NaN,NaN,2.351889,48.864062,75003,751031204,5.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,4.0,0.0,1.0,1.0,0.0,36.0,0.0,0.0,1.0
3,3,1,08/01/2020,Vente,370000.0,79.0,NaN,RUE,0420,DES ARCHIVES,75003.0,PARIS,75,103,NaN,AI,49,NaN,35,22.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,21.0,1.0,NaN,NaN,0.0,75103,75003 PARIS 03,79 RUE DES ARCHIVES 75003 PARIS,17619.047619,1,Paris,Île-de-France,0,NaN,NaN,2.359887,48.863220,75003,751031003,9.0,0.0,0.0,1.0,9.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,1.0,0.0,0.0,50.0,0.0,0.0,0.0
4,4,1,09/01/2020,Vente,741500.0,131.0,NaN,RUE,8525,SAINT DENIS,75001.0,PARIS,75,101,NaN,AQ,107,NaN,23,61.41,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,61.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,131 RUE SAINT DENIS 75001 PARIS,12155.737705,1,Paris,Île-de-France,0,NaN,NaN,2.347447,48.858758,75001,751010101,2.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,2.0,0.0,0.0,0.0,0.0,39.0,0.0,0.0,0.0

In [62]:
df_new = df_new.drop(columns = {'Unnamed: 0'})

In [63]:
pd.set_option('display.max_columns', None) 
df_new.head()

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain,Code commune INSEE,Ville,Adresse,Prix m2,Paris,dep_name,region_name,Mer,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,code_iris_clean,Alimentation,Aéroport,Baignade,Banques,Boulangerie,Camping,Cinéma,Collège ou lycée,Crèche,Ecole mat et primaire,Ecole sup,Etab hospi,Gare,Gare nationale,Hotels,Info touristique,Parcours sportif/santé,Pharmacie,Police ou gendarmerie,Port plaisance,Restaurants,Resto U,Résidence U,Salle multisport
0,1,02/01/2020,Vente,268800.0,14.0,NaN,RUE,0411,DE L'ARCADE,75008.0,PARIS,75,108,NaN,BS,136,NaN,31,NaN,8.0,22.72,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,24.0,1.0,NaN,NaN,0.0,75108,75008 PARIS 08,14 RUE DE L'ARCADE 75008 PARIS,11200.000000,1,Paris,Île-de-France,0,NaN,NaN,2.323688,48.871652,75008,751083106,5.0,0.0,0.0,14.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,6.0,0.0,2.0,0.0,0.0,93.0,0.0,0.0,0.0
1,1,06/01/2020,Vente,878378.0,9.0,NaN,BD,5888,DE LA MADELEINE,75001.0,PARIS,75,101,NaN,BC,41,NaN,14,66.64,15.0,NaN,40.0,NaN,NaN,NaN,NaN,NaN,3,2.0,Appartement,NaN,66.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,9 BD DE LA MADELEINE 75001 PARIS,13308.757576,1,Paris,Île-de-France,0,NaN,NaN,2.326961,48.869560,75001,751010402,4.0,0.0,0.0,22.0,5.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,12.0,8.0,0.0,4.0,1.0,0.0,87.0,0.0,0.0,0.0
2,1,10/01/2020,Vente,680000.0,10.0,NaN,RUE,1200,DU BOURG L'ABBE,75003.0,PARIS,75,103,NaN,AV,6,NaN,9,50.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,51.0,2.0,NaN,NaN,0.0,75103,75003 PARIS 03,10 RUE DU BOURG L'ABBE 75003 PARIS,13333.333333,1,Paris,Île-de-France,0,NaN,NaN,2.351889,48.864062,75003,751031204,5.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,4.0,0.0,1.0,1.0,0.0,36.0,0.0,0.0,1.0
3,1,08/01/2020,Vente,370000.0,79.0,NaN,RUE,0420,DES ARCHIVES,75003.0,PARIS,75,103,NaN,AI,49,NaN,35,22.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,21.0,1.0,NaN,NaN,0.0,75103,75003 PARIS 03,79 RUE DES ARCHIVES 75003 PARIS,17619.047619,1,Paris,Île-de-France,0,NaN,NaN,2.359887,48.863220,75003,751031003,9.0,0.0,0.0,1.0,9.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,1.0,0.0,0.0,50.0,0.0,0.0,0.0
4,1,09/01/2020,Vente,741500.0,131.0,NaN,RUE,8525,SAINT DENIS,75001.0,PARIS,75,101,NaN,AQ,107,NaN,23,61.41,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,61.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,131 RUE SAINT DENIS 75001 PARIS,12155.737705,1,Paris,Île-de-France,0,NaN,NaN,2.347447,48.858758,75001,751010101,2.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,2.0,0.0,0.0,0.0,0.0,39.0,0.0,0.0,0.0

In [64]:
df_new = df_new.drop(columns = {'No disposition', 'Nature mutation', 'No voie', 'B/T/Q', 'Code voie', 'Voie', 'Type de voie', 
                                'Code postal',
                               'Commune Alt', 'Code commune', 'Prefixe de section', 'Section', 'No plan', 'No Volume',
                               '1er lot', 'Surface Carrez du 1er lot', '2eme lot', 'Surface Carrez du 2eme lot',
                               '3eme lot', 'Surface Carrez du 3eme lot', '4eme lot', 'Surface Carrez du 4eme lot',
                               '5eme lot', 'Surface Carrez du 5eme lot', 'Code type local', 'Identifiant local',
                               'Nature culture', 'Nature culture speciale', 'Ville'})

KeyError: "['Commune Alt'] not found in axis"

In [65]:
df_new.head()

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain,Code commune INSEE,Ville,Adresse,Prix m2,Paris,dep_name,region_name,Mer,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,code_iris_clean,Alimentation,Aéroport,Baignade,Banques,Boulangerie,Camping,Cinéma,Collège ou lycée,Crèche,Ecole mat et primaire,Ecole sup,Etab hospi,Gare,Gare nationale,Hotels,Info touristique,Parcours sportif/santé,Pharmacie,Police ou gendarmerie,Port plaisance,Restaurants,Resto U,Résidence U,Salle multisport
0,1,02/01/2020,Vente,268800.0,14.0,NaN,RUE,0411,DE L'ARCADE,75008.0,PARIS,75,108,NaN,BS,136,NaN,31,NaN,8.0,22.72,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,24.0,1.0,NaN,NaN,0.0,75108,75008 PARIS 08,14 RUE DE L'ARCADE 75008 PARIS,11200.000000,1,Paris,Île-de-France,0,NaN,NaN,2.323688,48.871652,75008,751083106,5.0,0.0,0.0,14.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,6.0,0.0,2.0,0.0,0.0,93.0,0.0,0.0,0.0
1,1,06/01/2020,Vente,878378.0,9.0,NaN,BD,5888,DE LA MADELEINE,75001.0,PARIS,75,101,NaN,BC,41,NaN,14,66.64,15.0,NaN,40.0,NaN,NaN,NaN,NaN,NaN,3,2.0,Appartement,NaN,66.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,9 BD DE LA MADELEINE 75001 PARIS,13308.757576,1,Paris,Île-de-France,0,NaN,NaN,2.326961,48.869560,75001,751010402,4.0,0.0,0.0,22.0,5.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,12.0,8.0,0.0,4.0,1.0,0.0,87.0,0.0,0.0,0.0
2,1,10/01/2020,Vente,680000.0,10.0,NaN,RUE,1200,DU BOURG L'ABBE,75003.0,PARIS,75,103,NaN,AV,6,NaN,9,50.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,51.0,2.0,NaN,NaN,0.0,75103,75003 PARIS 03,10 RUE DU BOURG L'ABBE 75003 PARIS,13333.333333,1,Paris,Île-de-France,0,NaN,NaN,2.351889,48.864062,75003,751031204,5.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,4.0,0.0,1.0,1.0,0.0,36.0,0.0,0.0,1.0
3,1,08/01/2020,Vente,370000.0,79.0,NaN,RUE,0420,DES ARCHIVES,75003.0,PARIS,75,103,NaN,AI,49,NaN,35,22.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,21.0,1.0,NaN,NaN,0.0,75103,75003 PARIS 03,79 RUE DES ARCHIVES 75003 PARIS,17619.047619,1,Paris,Île-de-France,0,NaN,NaN,2.359887,48.863220,75003,751031003,9.0,0.0,0.0,1.0,9.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,1.0,0.0,0.0,50.0,0.0,0.0,0.0
4,1,09/01/2020,Vente,741500.0,131.0,NaN,RUE,8525,SAINT DENIS,75001.0,PARIS,75,101,NaN,AQ,107,NaN,23,61.41,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,61.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,131 RUE SAINT DENIS 75001 PARIS,12155.737705,1,Paris,Île-de-France,0,NaN,NaN,2.347447,48.858758,75001,751010101,2.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,2.0,0.0,0.0,0.0,0.0,39.0,0.0,0.0,0.0

In [66]:
df_new.shape

(539927, 74)

In [67]:
df_new =  df_new.dropna(axis = 0, how = 'all', subset = ['lat','lon','code_iris_clean'])
df_new.shape

(505089, 74)

## Ajout de la base de loyers 2018

In [68]:
loy = pd.read_csv('./databases/inter/03B - loyers_2018_par_commune_typelocal.csv')
loy = loy.rename(columns = {'INSEE': 'Code commune INSEE'})
loy.head()

  Code commune INSEE  loy_appart  loy_maison
0              01001    9.372335    8.191701
1              01002    8.635552    7.441199
2              01004   10.074507    8.411184
3              01005    9.372335    9.039551
4              01006    8.966955    8.058265

In [69]:
df_new = df_new.merge(loy, on = 'Code commune INSEE', how = "left")
df_new.head()

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain,Code commune INSEE,Ville,Adresse,Prix m2,Paris,dep_name,region_name,Mer,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,code_iris_clean,Alimentation,Aéroport,Baignade,Banques,Boulangerie,Camping,Cinéma,Collège ou lycée,Crèche,Ecole mat et primaire,Ecole sup,Etab hospi,Gare,Gare nationale,Hotels,Info touristique,Parcours sportif/santé,Pharmacie,Police ou gendarmerie,Port plaisance,Restaurants,Resto U,Résidence U,Salle multisport,loy_appart,loy_maison
0,1,02/01/2020,Vente,268800.0,14.0,NaN,RUE,0411,DE L'ARCADE,75008.0,PARIS,75,108,NaN,BS,136,NaN,31,NaN,8.0,22.72,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,24.0,1.0,NaN,NaN,0.0,75108,75008 PARIS 08,14 RUE DE L'ARCADE 75008 PARIS,11200.000000,1,Paris,Île-de-France,0,NaN,NaN,2.323688,48.871652,75008,751083106,5.0,0.0,0.0,14.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,6.0,0.0,2.0,0.0,0.0,93.0,0.0,0.0,0.0,35.002977,30.939697
1,1,06/01/2020,Vente,878378.0,9.0,NaN,BD,5888,DE LA MADELEINE,75001.0,PARIS,75,101,NaN,BC,41,NaN,14,66.64,15.0,NaN,40.0,NaN,NaN,NaN,NaN,NaN,3,2.0,Appartement,NaN,66.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,9 BD DE LA MADELEINE 75001 PARIS,13308.757576,1,Paris,Île-de-France,0,NaN,NaN,2.326961,48.869560,75001,751010402,4.0,0.0,0.0,22.0,5.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,12.0,8.0,0.0,4.0,1.0,0.0,87.0,0.0,0.0,0.0,36.654438,30.939697
2,1,10/01/2020,Vente,680000.0,10.0,NaN,RUE,1200,DU BOURG L'ABBE,75003.0,PARIS,75,103,NaN,AV,6,NaN,9,50.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,51.0,2.0,NaN,NaN,0.0,75103,75003 PARIS 03,10 RUE DU BOURG L'ABBE 75003 PARIS,13333.333333,1,Paris,Île-de-France,0,NaN,NaN,2.351889,48.864062,75003,751031204,5.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,4.0,0.0,1.0,1.0,0.0,36.0,0.0,0.0,1.0,34.206456,30.939697
3,1,08/01/2020,Vente,370000.0,79.0,NaN,RUE,0420,DES ARCHIVES,75003.0,PARIS,75,103,NaN,AI,49,NaN,35,22.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,21.0,1.0,NaN,NaN,0.0,75103,75003 PARIS 03,79 RUE DES ARCHIVES 75003 PARIS,17619.047619,1,Paris,Île-de-France,0,NaN,NaN,2.359887,48.863220,75003,751031003,9.0,0.0,0.0,1.0,9.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,1.0,0.0,0.0,50.0,0.0,0.0,0.0,34.206456,30.939697
4,1,09/01/2020,Vente,741500.0,131.0,NaN,RUE,8525,SAINT DENIS,75001.0,PARIS,75,101,NaN,AQ,107,NaN,23,61.41,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,61.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,131 RUE SAINT DENIS 75001 PARIS,12155.737705,1,Paris,Île-de-France,0,NaN,NaN,2.347447,48.858758,75001,751010101,2.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,2.0,0.0,0.0,0.0,0.0,39.0,0.0,0.0,0.0,36.654438,30.939697

In [70]:
# Champ "loyer" va contenir le "loy_maison" si le bien est une maison, "loy_appart" si le bien est un appartement
df_new['loyer'] = df_new.apply(lambda x: x['loy_maison'] if x['Type local'] == "Maison" else x['loy_appart'], axis = 1)
df_new = df_new.drop(columns = {'loy_appart', 'loy_maison'})
df_new.head()

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain,Code commune INSEE,Ville,Adresse,Prix m2,Paris,dep_name,region_name,Mer,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,code_iris_clean,Alimentation,Aéroport,Baignade,Banques,Boulangerie,Camping,Cinéma,Collège ou lycée,Crèche,Ecole mat et primaire,Ecole sup,Etab hospi,Gare,Gare nationale,Hotels,Info touristique,Parcours sportif/santé,Pharmacie,Police ou gendarmerie,Port plaisance,Restaurants,Resto U,Résidence U,Salle multisport,loyer
0,1,02/01/2020,Vente,268800.0,14.0,NaN,RUE,0411,DE L'ARCADE,75008.0,PARIS,75,108,NaN,BS,136,NaN,31,NaN,8.0,22.72,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,24.0,1.0,NaN,NaN,0.0,75108,75008 PARIS 08,14 RUE DE L'ARCADE 75008 PARIS,11200.000000,1,Paris,Île-de-France,0,NaN,NaN,2.323688,48.871652,75008,751083106,5.0,0.0,0.0,14.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,6.0,0.0,2.0,0.0,0.0,93.0,0.0,0.0,0.0,35.002977
1,1,06/01/2020,Vente,878378.0,9.0,NaN,BD,5888,DE LA MADELEINE,75001.0,PARIS,75,101,NaN,BC,41,NaN,14,66.64,15.0,NaN,40.0,NaN,NaN,NaN,NaN,NaN,3,2.0,Appartement,NaN,66.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,9 BD DE LA MADELEINE 75001 PARIS,13308.757576,1,Paris,Île-de-France,0,NaN,NaN,2.326961,48.869560,75001,751010402,4.0,0.0,0.0,22.0,5.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,12.0,8.0,0.0,4.0,1.0,0.0,87.0,0.0,0.0,0.0,36.654438
2,1,10/01/2020,Vente,680000.0,10.0,NaN,RUE,1200,DU BOURG L'ABBE,75003.0,PARIS,75,103,NaN,AV,6,NaN,9,50.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,51.0,2.0,NaN,NaN,0.0,75103,75003 PARIS 03,10 RUE DU BOURG L'ABBE 75003 PARIS,13333.333333,1,Paris,Île-de-France,0,NaN,NaN,2.351889,48.864062,75003,751031204,5.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,4.0,0.0,1.0,1.0,0.0,36.0,0.0,0.0,1.0,34.206456
3,1,08/01/2020,Vente,370000.0,79.0,NaN,RUE,0420,DES ARCHIVES,75003.0,PARIS,75,103,NaN,AI,49,NaN,35,22.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,21.0,1.0,NaN,NaN,0.0,75103,75003 PARIS 03,79 RUE DES ARCHIVES 75003 PARIS,17619.047619,1,Paris,Île-de-France,0,NaN,NaN,2.359887,48.863220,75003,751031003,9.0,0.0,0.0,1.0,9.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,1.0,0.0,0.0,50.0,0.0,0.0,0.0,34.206456
4,1,09/01/2020,Vente,741500.0,131.0,NaN,RUE,8525,SAINT DENIS,75001.0,PARIS,75,101,NaN,AQ,107,NaN,23,61.41,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,61.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,131 RUE SAINT DENIS 75001 PARIS,12155.737705,1,Paris,Île-de-France,0,NaN,NaN,2.347447,48.858758,75001,751010101,2.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,2.0,0.0,0.0,0.0,0.0,39.0,0.0,0.0,0.0,36.654438

# Ajout de la base Population

In [71]:
population = pd.read_csv('databases/population.csv', sep = ";", dtype = {'Population totale': int, 
                                                                         'Code commune INSEE': str})
population = population[['Code commune INSEE', 'Population totale']]
population.head()

  Code commune INSEE  Population totale
0              01001                789
1              01002                254
2              01004              14586
3              01005               1744
4              01006                118

In [72]:
df_new = df_new.merge(population, on = "Code commune INSEE", how = "left")

# Ajout de la base Salaires
Contient les salaires moyens horaires 2019 par departement issus de la base INSEE

In [73]:
salaire = pd.read_csv('databases/salaire.csv', sep = ";", decimal = ",", dtype = {'Code departement': str})
salaire = salaire[['SNHMO18', 'SNHMFO18', 'Code departement']]
salaire.head()

     SNHMO18   SNHMFO18 Code departement
0  11.531505  10.275121                1
1  11.502888  10.251496                2
2  11.176003  10.364809                3
3  11.242154   9.786999                4
4  11.372646   9.331007                5

In [74]:
df_new = df_new.merge(salaire, on = "Code departement", how = "left")

## Ajout de la base DPE (Diagnostics de performance énergétique)

Les diagnostics pouvant être faits en amont des ventes (une année au préalable potentiellement voire plus), nous utilisons l'intégralité de la base. 

Nous ferons le merge à partir des adresses, car nous partons également du principe que pour les appartements, les informations sont similaires d'un appartement à l'autre (année de construction de l'immeuble, date de l'installation électrique, isolation de l'immeuble, etc.)

In [75]:
import unidecode
import numpy as np

# Traitement des adresses de la base initiale pour le match avec la base DPE
df_new['Adresse'] = df_new['Adresse'].replace(',', ' ', regex=True).astype(str)
df_new['Adresse'] = df_new['Adresse'].apply(lambda x: unidecode.unidecode(x))
df_new['Adresse'] = df_new['Adresse'].replace('-', ' ', regex=True).astype(str)
df_new['Adresse'] = df_new['Adresse'].replace([' L ', ' D '], [' L\'', ' D\''], regex = True)
df_new['Adresse'].head()

# Traitement du code département, car va être important pour merger dépt par dépt avec la base DPE
df_new['Code departement'] = df_new['Code departement'].apply(lambda x: str(x).zfill(2))

df_new['code_iris_clean'] = df_new['code_iris_clean'].fillna(-1).astype(int).astype(str).replace('-1', np.nan)
df_new.head()

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain,Code commune INSEE,Ville,Adresse,Prix m2,Paris,dep_name,region_name,Mer,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,code_iris_clean,Alimentation,Aéroport,Baignade,Banques,Boulangerie,Camping,Cinéma,Collège ou lycée,Crèche,Ecole mat et primaire,Ecole sup,Etab hospi,Gare,Gare nationale,Hotels,Info touristique,Parcours sportif/santé,Pharmacie,Police ou gendarmerie,Port plaisance,Restaurants,Resto U,Résidence U,Salle multisport,loyer,Population totale,SNHMO18,SNHMFO18
0,1,02/01/2020,Vente,268800.0,14.0,NaN,RUE,0411,DE L'ARCADE,75008.0,PARIS,75,108,NaN,BS,136,NaN,31,NaN,8.0,22.72,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,24.0,1.0,NaN,NaN,0.0,75108,75008 PARIS 08,14 RUE DE L'ARCADE 75008 PARIS,11200.000000,1,Paris,Île-de-France,0,NaN,NaN,2.323688,48.871652,75008,751083106,5.0,0.0,0.0,14.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,6.0,0.0,2.0,0.0,0.0,93.0,0.0,0.0,0.0,35.002977,36827.0,11.110637,10.55109
1,1,06/01/2020,Vente,878378.0,9.0,NaN,BD,5888,DE LA MADELEINE,75001.0,PARIS,75,101,NaN,BC,41,NaN,14,66.64,15.0,NaN,40.0,NaN,NaN,NaN,NaN,NaN,3,2.0,Appartement,NaN,66.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,9 BD DE LA MADELEINE 75001 PARIS,13308.757576,1,Paris,Île-de-France,0,NaN,NaN,2.326961,48.869560,75001,751010402,4.0,0.0,0.0,22.0,5.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,12.0,8.0,0.0,4.0,1.0,0.0,87.0,0.0,0.0,0.0,36.654438,16236.0,11.110637,10.55109
2,1,10/01/2020,Vente,680000.0,10.0,NaN,RUE,1200,DU BOURG L'ABBE,75003.0,PARIS,75,103,NaN,AV,6,NaN,9,50.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,51.0,2.0,NaN,NaN,0.0,75103,75003 PARIS 03,10 RUE DU BOURG L'ABBE 75003 PARIS,13333.333333,1,Paris,Île-de-France,0,NaN,NaN,2.351889,48.864062,75003,751031204,5.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,4.0,0.0,1.0,1.0,0.0,36.0,0.0,0.0,1.0,34.206456,34305.0,11.110637,10.55109
3,1,08/01/2020,Vente,370000.0,79.0,NaN,RUE,0420,DES ARCHIVES,75003.0,PARIS,75,103,NaN,AI,49,NaN,35,22.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,21.0,1.0,NaN,NaN,0.0,75103,75003 PARIS 03,79 RUE DES ARCHIVES 75003 PARIS,17619.047619,1,Paris,Île-de-France,0,NaN,NaN,2.359887,48.863220,75003,751031003,9.0,0.0,0.0,1.0,9.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,1.0,0.0,0.0,50.0,0.0,0.0,0.0,34.206456,34305.0,11.110637,10.55109
4,1,09/01/2020,Vente,741500.0,131.0,NaN,RUE,8525,SAINT DENIS,75001.0,PARIS,75,101,NaN,AQ,107,NaN,23,61.41,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,61.0,2.0,NaN,NaN,0.0,75101,75001 PARIS 01,131 RUE SAINT DENIS 75001 PARIS,12155.737705,1,Paris,Île-de-France,0,NaN,NaN,2.347447,48.858758,75001,751010101,2.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,5.0,2.0,0.0,0.0,0.0,0.0,39.0,0.0,0.0,0.0,36.654438,16236.0,11.110637,10.55109

In [76]:
dpe = pd.read_csv('databases/dpe/dpe_france.csv')
dpe.shape

C:\Users\olivier\anaconda\envs\Geo\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (13,14) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

(9527755, 23)

In [77]:
dpe.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'consommation_energie',
       'classe_consommation_energie', 'estimation_ges',
       'classe_estimation_ges', 'annee_construction', 'surface_habitable',
       'commune', 'numero_rue', 'type_voie', 'nom_rue', 'etage', 'code_postal',
       'code_insee_commune_actualise', 'surface_baies_orientees_nord',
       'surface_baies_orientees_est_ouest', 'surface_baies_orientees_sud',
       'longitude', 'latitude', 'dep', 'Adresse', 'anciennete'],
      dtype='object')

In [78]:
# On ne conserve que les colonnes pertinentes
dpe_test = dpe[['dep', 'Adresse', 'anciennete', 'consommation_energie', 'classe_consommation_energie',
                'estimation_ges', 'classe_estimation_ges', 'surface_baies_orientees_sud']]

# On ne conserve que la première ligne trouvée (cela peut être encore amélioré)
dpe_test = dpe_test.drop_duplicates(subset = ['Adresse'], keep='first')  
dpe_test.head()

,dep,Adresse,anciennete,consommation_energie,classe_consommation_energie,estimation_ges,classe_estimation_ges,surface_baies_orientees_sud
0,1,212 CHE DE LA BRUYERE 212 CHE DE LA BRUYERE 16...,45,319.91,E,18.20,C,9.03
1,1,6 LOTS LE PARC DES ORMES 6 LOTS LE PARC DES OR...,17,148.09,C,34.65,D,2.76
2,1,VILLAGE D'EN HAUT 1340 ETREZ,21,210.00,D,11.00,C,0.00
3,1,9 CHE DE TRESIN 1100 OYONNAX,49,221.00,D,32.00,D,0.00
4,1,11 LOTS LE LAC 1400 CHATILLON SUR CHALARONNE,32,258.00,E,15.00,C,0.00

In [79]:
# Test utilisation classe consommation energie

# dpe_test['classe_consommation_energie'].value_counts()
# dpe_test = dpe_test[(dpe_test['classe_consommation_energie'] != "N") & (dpe_test['classe_consommation_energie'] != "-")]
# dpe_test['classe_consommation_energie'] = dpe_test['classe_consommation_energie'].replace(["A", "B", "C", "D", "E", "F", "G", "H", "I"], [0, 1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
# Faire en sorte que le code département soit toujours à deux chiffres
dpe_test['dep'] = dpe_test['dep'].apply(lambda x: str(x).zfill(2))
dpe_test.head()

,dep,Adresse,anciennete,consommation_energie,classe_consommation_energie,estimation_ges,classe_estimation_ges,surface_baies_orientees_sud
0,01,212 CHE DE LA BRUYERE 212 CHE DE LA BRUYERE 16...,45,319.91,E,18.20,C,9.03
1,01,6 LOTS LE PARC DES ORMES 6 LOTS LE PARC DES OR...,17,148.09,C,34.65,D,2.76
2,01,VILLAGE D'EN HAUT 1340 ETREZ,21,210.00,D,11.00,C,0.00
3,01,9 CHE DE TRESIN 1100 OYONNAX,49,221.00,D,32.00,D,0.00
4,01,11 LOTS LE LAC 1400 CHATILLON SUR CHALARONNE,32,258.00,E,15.00,C,0.00

In [81]:
dpe_test.shape

(5716565, 8)

In [82]:
# Merge de la base initiale avec la base DPE sur la base de l'adresse : boucle qui va tourner pour chaque département

merge = pd.DataFrame()

for i in range(1,96):
    try:
        i = str(i).zfill(2)
        df_temp = df_new[df_new['Code departement'] == i]
        dpe_temp = dpe_test[dpe_test['dep'] == i]
        merge_temp = df_temp.merge(dpe_temp, on = "Adresse", how = "left")
        merge = pd.concat([merge, merge_temp])
    except:
        pass

merge.shape

(501679, 85)

In [83]:
merge.head()

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Prefixe de section,Section,No plan,No Volume,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,3eme lot,Surface Carrez du 3eme lot,4eme lot,Surface Carrez du 4eme lot,5eme lot,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain,Code commune INSEE,Ville,Adresse,Prix m2,Paris,dep_name,region_name,Mer,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,code_iris_clean,Alimentation,Aéroport,Baignade,Banques,Boulangerie,Camping,Cinéma,Collège ou lycée,Crèche,Ecole mat et primaire,Ecole sup,Etab hospi,Gare,Gare nationale,Hotels,Info touristique,Parcours sportif/santé,Pharmacie,Police ou gendarmerie,Port plaisance,Restaurants,Resto U,Résidence U,Salle multisport,loyer,Population totale,SNHMO18,SNHMFO18,dep,anciennete,consommation_energie,classe_consommation_energie,estimation_ges,classe_estimation_ges,surface_baies_orientees_sud
0,1,09/01/2020,Vente,72000.0,5367.0,NaN,NaN,B107,LORETTE,1270.0,COLIGNY,01,108,NaN,AH,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,35.0,2.0,S,NaN,381.0,1108,1270 COLIGNY,5367 LORETTE 1270 COLIGNY,2057.142857,0,Ain,Auvergne-Rhône-Alpes,0,46.386664,5.330823,5.351500,46.380469,01270,11080000,1.0,0.0,0.0,2.0,2.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,4.0,0.0,0.0,1.0,NaN,NaN,11.531505,10.275121,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,06/01/2020,Vente,180300.0,31.0,NaN,RUE,0970,COMTE DE LA TEYSSONNIERE,1000.0,BOURG-EN-BRESSE,01,53,NaN,AI,138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,75.0,4.0,S,NaN,525.0,1053,1000 BOURG EN BRESSE,31 RUE COMTE DE LA TEYSSONNIERE 1000 BOURG EN ...,2404.000000,0,Ain,Auvergne-Rhône-Alpes,0,46.205152,5.246021,5.208966,46.197026,01000,10530203,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,NaN,NaN,11.531505,10.275121,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,06/01/2020,Vente,54800.0,6.0,NaN,AV,0770,DU CHAMP DE FOIRE,1000.0,BOURG-EN-BRESSE,01,53,NaN,BK,197,NaN,211,31.68,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,NaN,32.0,1.0,NaN,NaN,0.0,1053,1000 BOURG EN BRESSE,6 AV DU CHAMP DE FOIRE 1000 BOURG EN BRESSE,1712.500000,0,Ain,Auvergne-Rhône-Alpes,0,46.205152,5.246021,5.229923,46.206965,01000,10530101,3.0,0.0,0.0,15.0,9.0,0.0,1.0,1.0,2.0,3.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,1.0,0.0,69.0,0.0,0.0,0.0,NaN,NaN,11.531505,10.275121,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,13/01/2020,Vente,97000.0,16.0,NaN,RUE,1770,DES GRAVES,1000.0,BOURG-EN-BRESSE,01,53,NaN,AZ,476,NaN,8,78.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,NaN,92.0,3.0,NaN,NaN,0.0,1053,1000 BOURG EN BRESSE,16 RUE DES GRAVES 1000 BOURG EN BRESSE,1054.347826,0,Ain,Auvergne-Rhône-Alpes,0,46.205152,5.246021,5.232291,46.199495,01000,10530302,2.0,0.0,0.0,2.0,2.0,0.0,0.0,4.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,13.0,0.0,0.0,4.0,NaN,NaN,11.531505,10.275121,01,42.0,267.37,E,7.22,B,0.0
4,1,09/01/2020,Vente,215000.0,2.0,NaN,IMP,0140,DU COLOMBIER,1250.0,TOSSIAT,01,422,NaN,D,1121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,Maison,NaN,93.0,4.0,S,NaN,790.0,1422,1250 TOSSIAT,2 IMP DU COLOMBIER 1250 TOSSIAT,2311.827957,0,Ain,Auvergne-Rhône-Alpes,0,46.138479,5.304001,5.311045,46.141154,01250,14220000,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0,0.0,0.0,NaN,NaN,11.531505,10.275121,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Derniers traitements avant export

In [90]:
merge.to_csv('./databases/inter/03C - dvf_merged_' + year + '.csv')

In [86]:
merge.isna().sum()

No disposition                      0
Date mutation                       0
Nature mutation                     0
Valeur fonciere                     0
No voie                          1492
                                ...
consommation_energie           253068
classe_consommation_energie    253068
estimation_ges                 253068
classe_estimation_ges          253068
surface_baies_orientees_sud    282718
Length: 85, dtype: int64

In [87]:
# Nombre de lignes de la base initiale pour laquelle aucune correspondance DPE n'a été trouvée
nb_lines_ko = merge[merge['anciennete'].isna()].shape[0]
print('Il restera ' + str(merge.shape[0] - nb_lines_ko) + ' lignes')

Il restera 248611 lignes