In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('export_gps_iris_ALL.csv', dtype = {'Code postal 5 chiffres': str, 'Code commune INSEE': str,
                                             'code_iris_clean': str})
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'export_gps_iris_ALL.csv'

In [6]:
missing_iris = pd.read_csv('databases/gps_iris/iris_missing_completed.csv')
missing_iris.head()

C:\Users\olivier\anaconda\envs\Geo\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (9,10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Unnamed: 0,index,Adresse,Commune_Lat,Commune_Lon,lon,lat,Code departement,Code postal 5 chiffres,Code commune INSEE,code_iris_clean
0,0,5,CHAMP PORTIER 1370 VAL-REVERMONT,NaN,NaN,5.342953,46.264482,01,1370.0,01426,014260000
1,1,19,5340 IMP GRAND CHAMP 1310 SAINT-REMY,46.184664,5.167714,6.161794,49.174718,01,1310.0,01385,NaN
2,2,38,6058 OUSSIAT 1160 PONT-D AIN,NaN,NaN,5.361196,46.055795,01,1160.0,01304,013040000
3,3,42,5136 LE BOURG 1160 PRIAY,46.019752,5.285234,5.207310,46.069185,01,1160.0,01314,NaN
4,4,43,LE BOURG 1160 PRIAY,46.019752,5.285234,5.207310,46.069185,01,1160.0,01314,NaN

In [8]:
missing_iris = missing_iris.drop(columns = {'Unnamed: 0', 'index', 'Commune_Lat', 'Commune_Lon', 'lon', 'lat', 'Code departement',
                            'Code postal 5 chiffres', 'Code commune INSEE'})
missing_iris.head()

                                Adresse code_iris_clean
0      CHAMP PORTIER 1370 VAL-REVERMONT       014260000
1  5340 IMP GRAND CHAMP 1310 SAINT-REMY             NaN
2         6058  OUSSIAT 1160 PONT-D AIN       013040000
3             5136  LE BOURG 1160 PRIAY             NaN
4                   LE BOURG 1160 PRIAY             NaN

In [10]:
dvf = df.merge(missing_iris, on = "Adresse", how = "left")

,Unnamed: 0,Code service CH,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,...,Surface terrain,Adresse,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,Code commune INSEE,code_iris_clean_x,code_iris_clean_y
7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2020,...,55.0,CHAMP PORTIER 1370 VAL-REVERMONT,NaN,NaN,5.342953,46.264482,01370,01426,NaN,014260000
8,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2020,...,68.0,CHAMP PORTIER 1370 VAL-REVERMONT,NaN,NaN,5.342953,46.264482,01370,01426,NaN,014260000
66,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13/01/2020,...,924.0,6058 OUSSIAT 1160 PONT-D AIN,NaN,NaN,5.361196,46.055795,01160,01304,NaN,013040000
85,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17/01/2020,...,700.0,60 CHE DU MAS GAILLARD 1370 VAL-REVERMONT,NaN,NaN,5.336988,46.278457,01370,01426,NaN,014260000
86,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17/01/2020,...,1361.0,60 CHE DU MAS GAILLARD 1370 VAL-REVERMONT,NaN,NaN,5.336988,46.278457,01370,01426,NaN,014260000

In [12]:
dvf['code_iris_clean'] = dvf['code_iris_clean_y'].where(dvf['code_iris_clean_x'].isna(), dvf['code_iris_clean_x'])

In [14]:
dvf[dvf['code_iris_clean_y'].isna()].head()

,Unnamed: 0,Code service CH,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,...,Adresse,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,Code commune INSEE,code_iris_clean_x,code_iris_clean_y,code_iris_clean
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2020,...,FORTUNAT 1250 CEYZERIAT,46.183217,5.320072,5.323007,46.173753,01250,01072,010720000,NaN,010720000
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/01/2020,...,TERRES DES CINQ SAULES 1290 LAIZ,46.246992,4.899335,4.892457,46.246330,01290,01203,012030000,NaN,012030000
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/01/2020,...,BOIS DU CHAMP RION 1290 LAIZ,46.246992,4.899335,4.892457,46.246330,01290,01203,012030000,NaN,012030000
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/01/2020,...,EN COROBERT 1290 LAIZ,46.246992,4.899335,4.881913,46.248368,01290,01203,012030000,NaN,012030000
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/01/2020,...,TERRES DES CINQ SAULES 1290 LAIZ,46.246992,4.899335,4.892457,46.246330,01290,01203,012030000,NaN,012030000

In [15]:
dvf[dvf['code_iris_clean_x'].isna()].head()

,Unnamed: 0,Code service CH,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,...,Adresse,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,Code commune INSEE,code_iris_clean_x,code_iris_clean_y,code_iris_clean
7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2020,...,CHAMP PORTIER 1370 VAL-REVERMONT,NaN,NaN,5.342953,46.264482,01370,01426,NaN,014260000,014260000
8,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2020,...,CHAMP PORTIER 1370 VAL-REVERMONT,NaN,NaN,5.342953,46.264482,01370,01426,NaN,014260000,014260000
33,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,09/01/2020,...,5340 IMP GRAND CHAMP 1310 SAINT-REMY,46.184664,5.167714,6.161794,49.174718,01310,01385,NaN,NaN,NaN
66,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13/01/2020,...,6058 OUSSIAT 1160 PONT-D AIN,NaN,NaN,5.361196,46.055795,01160,01304,NaN,013040000,013040000
73,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15/01/2020,...,5136 LE BOURG 1160 PRIAY,46.019752,5.285234,5.207310,46.069185,01160,01314,NaN,NaN,NaN

In [16]:
dvf = dvf.drop(columns = {'code_iris_clean_x', 'code_iris_clean_y'})
dvf.head()

,Unnamed: 0,Code service CH,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,...,Nature culture speciale,Surface terrain,Adresse,Commune_Lat,Commune_Lon,lon,lat,Code postal 5 chiffres,Code commune INSEE,code_iris_clean
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2020,...,NaN,1061.0,FORTUNAT 1250 CEYZERIAT,46.183217,5.320072,5.323007,46.173753,01250,01072,010720000
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/01/2020,...,NaN,85.0,TERRES DES CINQ SAULES 1290 LAIZ,46.246992,4.899335,4.892457,46.246330,01290,01203,012030000
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/01/2020,...,NaN,1115.0,BOIS DU CHAMP RION 1290 LAIZ,46.246992,4.899335,4.892457,46.246330,01290,01203,012030000
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/01/2020,...,NaN,1940.0,EN COROBERT 1290 LAIZ,46.246992,4.899335,4.881913,46.248368,01290,01203,012030000
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/01/2020,...,NaN,1148.0,TERRES DES CINQ SAULES 1290 LAIZ,46.246992,4.899335,4.892457,46.246330,01290,01203,012030000

In [17]:
dvf.to_csv('dvf_out_2020_cleaniris.csv')

In [18]:
dvf['code_iris_clean'].isna().sum()

216012